mkdir data
cd data
wget http://storage.jd.com/jdrec-csv/train_0.csv
wget http://storage.jd.com/jdrec-csv/train_1.csv
wget http://storage.jd.com/jdrec-csv/train_2.csv
wget http://storage.jd.com/jdrec-csv/train_3.csv
wget http://storage.jd.com/jdrec-csv/train_4.csv
wget http://storage.jd.com/jdrec-csv/train_5.csv
wget http://storage.jd.com/jdrec-csv/train_6.csv
wget http://storage.jd.com/jdrec-csv/train_7.csv
wget http://storage.jd.com/jdrec-csv/train_8.csv
wget http://storage.jd.com/jdrec-csv/test.csv
cd -
echo Done